"""init db

Revision ID: 8ca7124ef7aa
Revises: 
Create Date: 2026-09-14 20:35:48.862940

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '8ca7124ef7aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('category_details', sa.JSON(), nullable=False),
    sa.Column('commune_id', sa.UUID(), nullable=False, foreign_key='commune.id'),
    sa.PrimaryKeyConstraint('id', 'commune_id')
    )
    op.create_table('channel',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('commune_id', sa.UUID(), nullable=False, foreign_key='commune.id'),
    sa.Column('category_id', sa.UUID(), nullable=False, foreign_key='category.id'),
    sa.Column('mls_details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'commune_id', 'category_id')
    )
    op.create_table('commune',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('commune_details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False, foreign_key='user.id'),
    sa.Column('channel_id', sa.UUID(), nullable=False, foreign_key='channel.id'),
    sa.PrimaryKeyConstraint('id', 'owner_id', 'channel_id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('user_details', sa.JSON(), nullable=False),
    sa.Column('mls_details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userscommuneslink',
    sa.Column('user_id', sa.UUID(), nullable=False, foreign_key='user.id'),
    sa.Column('commune_id', sa.UUID(), nullable=False, foreign_key='commune.id'),
    sa.PrimaryKeyConstraint('user_id', 'commune_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userscommuneslink')
    op.drop_table('user')
    op.drop_table('message')
    op.drop_table('commune')
    op.drop_table('channel')
    op.drop_table('category')
    # ### end Alembic commands ###
