syntax = "proto3";
package models;


message User {
  string uuid7 = 1;
  string display_name = 2;
}

message Channel {
  string uuid7 = 1;
  string display_name = 2;
  Commune commune = 3;
}

message Commune {
  string uuid7 = 1;
  string display_name = 2;
}

message TextMessage {
  string uuid7 = 1;
  User from = 2;
  Commune destination = 3;
  string content = 4;
}

message UserCommunes {
  User user = 1;
  [Commune] communes = 2;
}

message CommuneUsers {
  Commune commune = 1;
  [User] users = 2;
}


